customhost = "employee.cbcanlehwrv2.ap-south-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "employee"
custombucket = "addemployeesanthosh30"
customregion = "ap-south-1"
